server:
  applicationConnectors:
    - type: http
      port: ${MARQUEZ_API_PORT}
  adminConnectors:
    - type: http
      port: ${MARQUEZ_ADMIN_PORT}
  applicationContextPath: /
  adminContextPath: /

db:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://marquez-db:5432/${MARQUEZ_DB_NAME}
  user: ${MARQUEZ_DB_USER}
  password: ${MARQUEZ_DB_PASSWORD}
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* Marquez Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  checkConnectionOnBorrow: true